// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAawInhiaS_OReC07m_cE4DADJmy7xifSQ',
    appId: '1:981649454373:web:27a06bc049746713c356cc',
    messagingSenderId: '981649454373',
    projectId: 'backend-27461',
    authDomain: 'backend-27461.firebaseapp.com',
    storageBucket: 'backend-27461.appspot.com',
    measurementId: 'G-YZDWT84R13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbwhUCufUUzKiaW55qYID7_Hyq0AwsmS0',
    appId: '1:981649454373:android:371ff8220ac4ab33c356cc',
    messagingSenderId: '981649454373',
    projectId: 'backend-27461',
    storageBucket: 'backend-27461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeEX9_7UWL3Xne2AqVSNMFwSuU84euldg',
    appId: '1:981649454373:ios:52e475deb38979cdc356cc',
    messagingSenderId: '981649454373',
    projectId: 'backend-27461',
    storageBucket: 'backend-27461.appspot.com',
    iosClientId: '981649454373-3qprvc229r44hmlcq05o5g7p9kfi6925.apps.googleusercontent.com',
    iosBundleId: 'com.example.patreonclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeEX9_7UWL3Xne2AqVSNMFwSuU84euldg',
    appId: '1:981649454373:ios:52e475deb38979cdc356cc',
    messagingSenderId: '981649454373',
    projectId: 'backend-27461',
    storageBucket: 'backend-27461.appspot.com',
    iosClientId: '981649454373-3qprvc229r44hmlcq05o5g7p9kfi6925.apps.googleusercontent.com',
    iosBundleId: 'com.example.patreonclone',
  );
}
